FROM python:latest

LABEL image.author.name "Micah Fletcher"
LABEL image.author.email "micahpfletcher@gmail.com"

COPY SMaSH.py SMaSH.py

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt